package entity;
// Generated May 5, 2017 10:44:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kupci generated by hbm2java
 */
@Entity
@Table(name="kupci"
    ,catalog="web_store"
)
public class Kupci  implements java.io.Serializable {


     private int idkupci;
     private String ime;
     private String email;
     private String adresa;
     private String brojTelefona;
     private int idproizvodi;

    public Kupci() {
    }

    public Kupci(int idkupci, String ime, String email, String adresa, String brojTelefona, int idproizvodi) {
       this.idkupci = idkupci;
       this.ime = ime;
       this.email = email;
       this.adresa = adresa;
       this.brojTelefona = brojTelefona;
       this.idproizvodi = idproizvodi;
    }
   
     @Id 

    
    @Column(name="idkupci", unique=true, nullable=false)
    public int getIdkupci() {
        return this.idkupci;
    }
    
    public void setIdkupci(int idkupci) {
        this.idkupci = idkupci;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="adresa", nullable=false, length=45)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="broj_telefona", nullable=false, length=45)
    public String getBrojTelefona() {
        return this.brojTelefona;
    }
    
    public void setBrojTelefona(String brojTelefona) {
        this.brojTelefona = brojTelefona;
    }

    
    @Column(name="idproizvodi", nullable=false)
    public int getIdproizvodi() {
        return this.idproizvodi;
    }
    
    public void setIdproizvodi(int idproizvodi) {
        this.idproizvodi = idproizvodi;
    }




}


