package entity;
// Generated May 5, 2017 10:44:28 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Proizvodi generated by hbm2java
 */
@Entity
@Table(name="proizvodi"
    ,catalog="web_store"
)
public class Proizvodi  implements java.io.Serializable {


     private Integer idproizvodi;
     private String naziv;
     private String opis;
     private int kolicina;
     private double cena;

    public Proizvodi() {
    }

    public Proizvodi(String naziv, String opis, int kolicina, double cena) {
       this.naziv = naziv;
       this.opis = opis;
       this.kolicina = kolicina;
       this.cena = cena;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproizvodi", unique=true, nullable=false)
    public Integer getIdproizvodi() {
        return this.idproizvodi;
    }
    
    public void setIdproizvodi(Integer idproizvodi) {
        this.idproizvodi = idproizvodi;
    }

    
    @Column(name="naziv", nullable=false, length=45)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="opis", nullable=false, length=45)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="kolicina", nullable=false)
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }

    
    @Column(name="cena", nullable=false, precision=22, scale=0)
    public double getCena() {
        return this.cena;
    }
    
    public void setCena(double cena) {
        this.cena = cena;
    }




}


